suspicousFiles:
  - Photo.scr
  - IMG001.exe
  - info.zip
  - w0000000t.php

downloadToCheck: true # download files to /tmp to check for viruses
suspiciousFileExtensions: # download only these file types for virus checking
  - exe
  - scr
  - zip